#ifndef AMBER_NATIVE_H
#define AMBER_NATIVE_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Free a string previously returned by any amber FFI function.
 * Passing null is safe (no-op).
 */
void amber_free_string(char *s);

/**
 * Free a byte buffer previously returned by any amber FFI function.
 * Passing null data is safe (no-op). `len` must be the length returned
 * alongside the pointer.
 */
void amber_free_bytes(uint8_t *data, uintptr_t len);

/**
 * Parse markdown text to packed binary AST blob.
 * Returns allocated bytes via (ptr, out_len). Caller frees with amber_free_bytes.
 * Returns null ptr on error.
 */
uint8_t *amber_markdown_parse(const char *text, uintptr_t *out_len);

/**
 * Parse markdown text to HTML string.
 * Returns allocated C string. Caller frees with amber_free_string.
 * Returns null on error.
 */
char *amber_markdown_to_html(const char *text);

/**
 * Preprocess markdown (LaTeX conversion, bare URL linkify).
 * Returns allocated C string. Caller frees with amber_free_string.
 * Returns null on error.
 */
char *amber_markdown_preprocess(const char *input);

/**
 * Syntax-highlight code for the given language, returning packed binary token blob.
 * Returns allocated bytes via (ptr, out_len). Caller frees with amber_free_bytes.
 * Returns null ptr on error.
 */
uint8_t *amber_highlight(const char *code, const char *language, uintptr_t *out_len);

/**
 * Get the list of supported language identifiers.
 * Returns a null-terminated C string with language names separated by `\n`.
 * Returns allocated C string. Caller frees with amber_free_string.
 * Returns null on error.
 */
char *amber_highlight_supported_languages(void);

/**
 * Normalize HTML for diff comparison.
 * Returns allocated C string. Caller frees with amber_free_string.
 * Returns null on error.
 */
char *amber_html_diff_normalize(const char *html);

/**
 * Extract readable article from HTML.
 *
 * Output is a JSON string with fields: title, content_html, content_text, section_count.
 * Returns allocated C string. Caller frees with amber_free_string.
 * Returns null on error.
 */
char *amber_reader_extract(const char *html, const char *base_url);

/**
 * Parse a DOCX file to markdown.
 * `path` is a UTF-8 file path.
 * Returns allocated C string (markdown content or error sentinel).
 * Caller frees with amber_free_string. Returns null on error.
 */
char *amber_parse_docx(const char *path);

/**
 * Parse a PPTX file to markdown.
 */
char *amber_parse_pptx(const char *path);

/**
 * Parse an EPUB file to markdown.
 */
char *amber_parse_epub(const char *path);

/**
 * Parse an XLSX file to markdown.
 */
char *amber_parse_xlsx(const char *path);

/**
 * Apply a pipeline of regex find-replace rules sequentially.
 *
 * `find_patterns` and `replacements` are null-terminated C string arrays
 * (each element is a C string, terminated by a null pointer). They must
 * have the same number of elements.
 *
 * Returns allocated C string. Caller frees with amber_free_string.
 * Returns null on error.
 */
char *amber_regex_apply(const char *input,
                        const char *const *find_patterns,
                        const char *const *replacements);

/**
 * Derive a key using PBKDF2-HMAC-SHA256.
 *
 * Returns allocated bytes via (ptr, out_len). Caller frees with amber_free_bytes.
 * Returns null ptr on error (e.g. iterations <= 0 or key_size_bytes <= 0).
 */
uint8_t *amber_pbkdf2_hmac_sha256(const char *passphrase,
                                  const uint8_t *salt,
                                  uintptr_t salt_len,
                                  uint32_t iterations,
                                  uintptr_t key_size_bytes,
                                  uintptr_t *out_len);

/**
 * AES-256-GCM encrypt.
 *
 * Returns ciphertext || 16-byte auth tag via (ptr, out_len).
 * Caller frees with amber_free_bytes. Returns null on error.
 */
uint8_t *amber_aes_gcm_encrypt(const uint8_t *plaintext,
                               uintptr_t plaintext_len,
                               const uint8_t *key,
                               uintptr_t key_len,
                               const uint8_t *iv,
                               uintptr_t iv_len,
                               uintptr_t *out_len);

/**
 * AES-256-GCM decrypt.
 *
 * Returns plaintext via (ptr, out_len). Returns null on auth failure.
 * Caller frees with amber_free_bytes.
 */
uint8_t *amber_aes_gcm_decrypt(const uint8_t *ciphertext,
                               uintptr_t ciphertext_len,
                               const uint8_t *key,
                               uintptr_t key_len,
                               const uint8_t *iv,
                               uintptr_t iv_len,
                               uintptr_t *out_len);

/**
 * SHA-256 hash.
 *
 * Returns 32 bytes via (ptr, out_len). Caller frees with amber_free_bytes.
 */
uint8_t *amber_sha256(const uint8_t *data, uintptr_t data_len, uintptr_t *out_len);

/**
 * HMAC-SHA256.
 *
 * Returns 32 bytes via (ptr, out_len). Caller frees with amber_free_bytes.
 */
uint8_t *amber_hmac_sha256(const uint8_t *key,
                           uintptr_t key_len,
                           const uint8_t *message,
                           uintptr_t message_len,
                           uintptr_t *out_len);

/**
 * Evaluate a JSON expression against a root JSON object.
 *
 * Returns allocated C string (result). Caller frees with amber_free_string.
 * Returns null on error.
 */
char *amber_json_expr_evaluate(const char *root_json, const char *expr);

/**
 * Check if a JSON expression is syntactically valid.
 *
 * Returns 1 for valid, 0 for invalid.
 */
int32_t amber_json_expr_is_valid(const char *expr);

/**
 * Count tokens for the given tokenizer ID and text.
 *
 * Returns the token count, or -1 on error.
 */
int64_t amber_tokenizer_count(const char *tokenizer_id, const char *text);

#endif  /* AMBER_NATIVE_H */
